// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjbrqwnssludkegflmfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqYnJxd25zc2x1ZGtlZ2ZsbWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTU1NTksImV4cCI6MjA3MTM3MTU1OX0.cECB9lrmuErDFqP7vIImWqX1Uyd3lg3tqMk22Mpm30o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});